# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drug_design_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReactionMonitor(object):
    def setupUi(self, ReactionMonitor):
        ReactionMonitor.setObjectName("ReactionMonitor")
        ReactionMonitor.resize(1760, 833)
        self.centralwidget = QtWidgets.QWidget(ReactionMonitor)
        self.centralwidget.setObjectName("centralwidget")
        self.raman_get = QtWidgets.QPushButton(self.centralwidget)
        self.raman_get.setGeometry(QtCore.QRect(380, 680, 151, 81))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.raman_get.setFont(font)
        self.raman_get.setObjectName("raman_get")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1020, 330, 251, 51))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ftir_get = QtWidgets.QPushButton(self.centralwidget)
        self.ftir_get.setGeometry(QtCore.QRect(380, 270, 151, 81))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.ftir_get.setFont(font)
        self.ftir_get.setObjectName("ftir_get")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1010, 710, 251, 51))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ftir_spec = QtWidgets.QLabel(self.centralwidget)
        self.ftir_spec.setGeometry(QtCore.QRect(550, 20, 1181, 321))
        self.ftir_spec.setObjectName("ftir_spec")
        self.raman_spec = QtWidgets.QLabel(self.centralwidget)
        self.raman_spec.setGeometry(QtCore.QRect(551, 404, 1171, 311))
        self.raman_spec.setObjectName("raman_spec")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 20, 321, 16))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(29, 380, 321, 16))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(21, 27, 20, 361))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(340, 28, 20, 361))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 30, 251, 51))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 240, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 290, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 340, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.switch1 = QtWidgets.QPushButton(self.centralwidget)
        self.switch1.setGeometry(QtCore.QRect(109, 489, 51, 28))
        self.switch1.setObjectName("switch1")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(340, 422, 20, 321))
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(110, 425, 171, 51))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(30, 415, 321, 16))
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(29, 735, 321, 16))
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(22, 421, 20, 321))
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(50, 488, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(50, 538, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.switch2 = QtWidgets.QPushButton(self.centralwidget)
        self.switch2.setGeometry(QtCore.QRect(109, 539, 51, 28))
        self.switch2.setObjectName("switch2")
        self.switch3 = QtWidgets.QPushButton(self.centralwidget)
        self.switch3.setGeometry(QtCore.QRect(109, 588, 51, 28))
        self.switch3.setObjectName("switch3")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(50, 587, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.switch4 = QtWidgets.QPushButton(self.centralwidget)
        self.switch4.setGeometry(QtCore.QRect(109, 639, 51, 28))
        self.switch4.setObjectName("switch4")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(50, 638, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(50, 692, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.switch5 = QtWidgets.QPushButton(self.centralwidget)
        self.switch5.setGeometry(QtCore.QRect(109, 693, 51, 28))
        self.switch5.setObjectName("switch5")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(212, 488, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(212, 692, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.switch8 = QtWidgets.QPushButton(self.centralwidget)
        self.switch8.setGeometry(QtCore.QRect(271, 588, 51, 28))
        self.switch8.setObjectName("switch8")
        self.switch7 = QtWidgets.QPushButton(self.centralwidget)
        self.switch7.setGeometry(QtCore.QRect(271, 539, 51, 28))
        self.switch7.setObjectName("switch7")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(212, 538, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.switch10 = QtWidgets.QPushButton(self.centralwidget)
        self.switch10.setGeometry(QtCore.QRect(271, 693, 51, 28))
        self.switch10.setObjectName("switch10")
        self.switch6 = QtWidgets.QPushButton(self.centralwidget)
        self.switch6.setGeometry(QtCore.QRect(271, 489, 51, 28))
        self.switch6.setObjectName("switch6")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(212, 638, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.switch9 = QtWidgets.QPushButton(self.centralwidget)
        self.switch9.setGeometry(QtCore.QRect(271, 639, 51, 28))
        self.switch9.setObjectName("switch9")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(212, 587, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.temp_display = QtWidgets.QLabel(self.centralwidget)
        self.temp_display.setGeometry(QtCore.QRect(240, 80, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.temp_display.setFont(font)
        self.temp_display.setObjectName("temp_display")
        self.flow_display = QtWidgets.QLabel(self.centralwidget)
        self.flow_display.setGeometry(QtCore.QRect(230, 240, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.flow_display.setFont(font)
        self.flow_display.setObjectName("flow_display")
        self.pressure_display = QtWidgets.QLabel(self.centralwidget)
        self.pressure_display.setGeometry(QtCore.QRect(230, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pressure_display.setFont(font)
        self.pressure_display.setObjectName("pressure_display")
        self.Stir_display = QtWidgets.QLabel(self.centralwidget)
        self.Stir_display.setGeometry(QtCore.QRect(230, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Stir_display.setFont(font)
        self.Stir_display.setObjectName("Stir_display")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(220, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.ph_display = QtWidgets.QLabel(self.centralwidget)
        self.ph_display.setGeometry(QtCore.QRect(230, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.ph_display.setFont(font)
        self.ph_display.setObjectName("ph_display")
        self.e_stop = QtWidgets.QPushButton(self.centralwidget)
        self.e_stop.setGeometry(QtCore.QRect(380, 20, 151, 81))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.e_stop.setFont(font)
        self.e_stop.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.e_stop.setObjectName("e_stop")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.set_temp = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.set_temp.setGeometry(QtCore.QRect(200, 110, 81, 31))
        self.set_temp.setDecimals(1)
        self.set_temp.setMaximum(340.0)
        self.set_temp.setSingleStep(5.0)
        self.set_temp.setObjectName("set_temp")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.set_stir = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.set_stir.setGeometry(QtCore.QRect(200, 190, 81, 31))
        self.set_stir.setDecimals(1)
        self.set_stir.setMaximum(3000.0)
        self.set_stir.setSingleStep(50.0)
        self.set_stir.setObjectName("set_stir")
        self.heat_switch = QtWidgets.QPushButton(self.centralwidget)
        self.heat_switch.setGeometry(QtCore.QRect(289, 111, 51, 28))
        self.heat_switch.setObjectName("heat_switch")
        self.stir_switch = QtWidgets.QPushButton(self.centralwidget)
        self.stir_switch.setGeometry(QtCore.QRect(289, 192, 51, 28))
        self.stir_switch.setObjectName("stir_switch")
        ReactionMonitor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReactionMonitor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1760, 26))
        self.menubar.setObjectName("menubar")
        self.menuFlow_Control = QtWidgets.QMenu(self.menubar)
        self.menuFlow_Control.setObjectName("menuFlow_Control")
        self.menuSingle_Steps = QtWidgets.QMenu(self.menubar)
        self.menuSingle_Steps.setObjectName("menuSingle_Steps")
        self.menuDebugger = QtWidgets.QMenu(self.menubar)
        self.menuDebugger.setObjectName("menuDebugger")
        ReactionMonitor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReactionMonitor)
        self.statusbar.setObjectName("statusbar")
        ReactionMonitor.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFlow_Control.menuAction())
        self.menubar.addAction(self.menuSingle_Steps.menuAction())
        self.menubar.addAction(self.menuDebugger.menuAction())

        self.retranslateUi(ReactionMonitor)
        QtCore.QMetaObject.connectSlotsByName(ReactionMonitor)

    def retranslateUi(self, ReactionMonitor):
        _translate = QtCore.QCoreApplication.translate
        ReactionMonitor.setWindowTitle(_translate("ReactionMonitor", "Reaction Monitor"))
        self.raman_get.setText(_translate("ReactionMonitor", "Get Raman"))
        self.label_2.setText(_translate("ReactionMonitor", "RT-FTIR Spectrum"))
        self.ftir_get.setText(_translate("ReactionMonitor", "Get FTIR"))
        self.label_3.setText(_translate("ReactionMonitor", "RT-Raman Spectrum"))
        self.ftir_spec.setText(_translate("ReactionMonitor", "TextLabel"))
        self.raman_spec.setText(_translate("ReactionMonitor", "TextLabel"))
        self.label_4.setText(_translate("ReactionMonitor", "Reaction Monitor"))
        self.label.setText(_translate("ReactionMonitor", "Current Temp."))
        self.label_5.setText(_translate("ReactionMonitor", "Flow Speed"))
        self.label_6.setText(_translate("ReactionMonitor", "Pipe Pressure"))
        self.label_7.setText(_translate("ReactionMonitor", "Current Stir"))
        self.label_8.setText(_translate("ReactionMonitor", "PH Value"))
        self.switch1.setText(_translate("ReactionMonitor", "OFF"))
        self.label_10.setText(_translate("ReactionMonitor", "Pump Control"))
        self.label_14.setText(_translate("ReactionMonitor", "CH1"))
        self.label_15.setText(_translate("ReactionMonitor", "CH2"))
        self.switch2.setText(_translate("ReactionMonitor", "OFF"))
        self.switch3.setText(_translate("ReactionMonitor", "OFF"))
        self.label_16.setText(_translate("ReactionMonitor", "CH3"))
        self.switch4.setText(_translate("ReactionMonitor", "OFF"))
        self.label_17.setText(_translate("ReactionMonitor", "CH4"))
        self.label_18.setText(_translate("ReactionMonitor", "CH5"))
        self.switch5.setText(_translate("ReactionMonitor", "OFF"))
        self.label_19.setText(_translate("ReactionMonitor", "CH6"))
        self.label_20.setText(_translate("ReactionMonitor", "CH10"))
        self.switch8.setText(_translate("ReactionMonitor", "OFF"))
        self.switch7.setText(_translate("ReactionMonitor", "OFF"))
        self.label_21.setText(_translate("ReactionMonitor", "CH7"))
        self.switch10.setText(_translate("ReactionMonitor", "OFF"))
        self.switch6.setText(_translate("ReactionMonitor", "OFF"))
        self.label_22.setText(_translate("ReactionMonitor", "CH9"))
        self.switch9.setText(_translate("ReactionMonitor", "OFF"))
        self.label_23.setText(_translate("ReactionMonitor", "CH8"))
        self.temp_display.setText(_translate("ReactionMonitor", "18.9 C"))
        self.flow_display.setText(_translate("ReactionMonitor", "0.6 ml/min"))
        self.pressure_display.setText(_translate("ReactionMonitor", "0.151 MPA"))
        self.Stir_display.setText(_translate("ReactionMonitor", "450 RPM"))
        self.ph_display.setText(_translate("ReactionMonitor", "2.35"))
        self.e_stop.setText(_translate("ReactionMonitor", "E-Stop"))
        self.label_9.setText(_translate("ReactionMonitor", "Set Temp"))
        self.label_11.setText(_translate("ReactionMonitor", "Set Stir"))
        self.heat_switch.setText(_translate("ReactionMonitor", "OFF"))
        self.stir_switch.setText(_translate("ReactionMonitor", "OFF"))
        self.menuFlow_Control.setTitle(_translate("ReactionMonitor", "Flow Control"))
        self.menuSingle_Steps.setTitle(_translate("ReactionMonitor", "Single Steps"))
        self.menuDebugger.setTitle(_translate("ReactionMonitor", "Debugger"))

